CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'naykim'@'%' IDENTIFIED BY '4242';
GRANT ALL PRIVILEGES ON wordpress.* TO 'naykim'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '4242';